name: Go Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: go build
        run: go build cmd/main.go

      - name: go vet
        run: go vet -v ./...

      - name: go staticcheck
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1"
          install-go: false
